[package]
name = "rqlite-rs-macros"
version = "0.2.1"
edition = "2021"
publish = true
license = "MIT"
description = "Proc-macros for rqlite-rs"
repository = "https://github.com/tomvoet/rqlite-rs"
readme = "../README.md"
keywords = ["rqlite", "database", "async"]
categories = ["database", "asynchronous"]
authors = ["Tom Voet <tomvoet@pm.me>"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
rqlite-rs-core = { version = "0.2.2", path = "../rqlite-rs-core" }
syn = { version = "2.0.52", features = ["full", "parsing"] }
