[package]
name = "rqlite-rs"
version = "0.3.7"
edition = "2021"
publish = true
license = "MIT"
description = "Async rqlite client for Rust"
repository = "https://github.com/tomvoet/rqlite-rs"
readme = "../README.md"
keywords = ["rqlite", "database", "async"]
categories = ["database", "asynchronous"]
authors = ["Tom Voet <tomvoet@pm.me>"]
documentation = "https://docs.rs/rqlite-rs/"

[features]
default = ["macros", "native-tls"]

native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

macros = ["rqlite-rs-macros"]

[dependencies]
rqlite-rs-macros = { version = "0.2.3", path = "../rqlite-rs-macros", optional = true }
rqlite-rs-core = { version = "0.2.4", path = "../rqlite-rs-core" }
reqwest = { version = "0.12.2", default-features = false }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
