[package]
name = "rqlite-rs"
version = "0.3.0"
edition = "2021"
publish = true
license = "MIT"
description = "Async rqlite client for Rust"
repository = "https://github.com/tomvoet/rqlite-rs"
readme = "../README.md"
keywords = ["rqlite", "database", "async"]
categories = ["database", "asynchronous"]
authors = ["Tom Voet <tomvoet@pm.me>"]
documentation = "https://docs.rs/rqlite-rs/"

[features]
default = []
macros = ["rqlite-rs-macros"]


[dependencies]
rqlite-rs-macros = { version = "0.2.2", path = "../rqlite-rs-macros", optional = true }
rqlite-rs-core = { version = "0.2.3", path = "../rqlite-rs-core" }
anyhow = "1.0.80"
reqwest = { version = "0.11.25" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
